### ISSUE TITLE
why is there a symmetric flip in ofdm.time_to_frequency_domain( ... ) ?

### ISSUE THREAD

**Issue by shuwang1** [ctarver/phypy#4]
* PhyPy version:
* Python version:
* Operating System:

### Description
At first, I should say, a great job.

when I was trying to generate OFDM symbols and demodulate OFDM symbols and calculate evm, I noticed that you have a frequency-domain flip in OFDM.time_to_frequency_domain() function. Why is that?

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ctarver** [comment]
Hi,

I'm not actively developing this right now and don't have free time to investigate. 

First, If I remember correctly, there is a bug somewhere in the OFDM, so don't trust anything too much.

Secondly, If I were to guess what you're asking about, this goes with how we index subcarriers vs how we load an ifft/fft. I like to index subcarriers with 0 being the subcarrier with the lowest frequency and 1199 (in the case of a 20 MHz LTE like signal) being the final subcarrier. We load our subcarriers onto an IFFT with the size of the next power of 2 which is 2048. For the IFFT and FFT, the negative frequency components are the last n/2 bins. Hence, the indexing becomes confusing. 

To have subcarrier 0 show up as the left-most subcarrier when we actually transmit, we need to load it into ifft bin 2047-600. We keep on increasing until we fill up all of the ifft bins corresponding to the negative frequencies. Then we skip ifft bin 0 because it represents DC. Then we continue filling in the ifft bin1 with subcarrier 600 (it's possible that I am +/- 1 in my indexing here).

**Comment by shuwang1** [comment]
Sorry ... my brain was occupied by some other issues from my project and for some reason .. and so, I think  I asked the stupid question above. Cheers.
